# Generated by Django 4.2 on 2024-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tz_database', '0003_goods_image_alter_category_name_alter_goods_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
