# Generated by Django 4.2 on 2024-06-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tz_database', '0005_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot_tz_database.subcategory'),
            preserve_default=False,
        ),
    ]
